const TOGGLE_THEME = 'TOGGLE_THEME';
const LOGIN_USER = 'LOGIN_USER';
const ADD_COMPANY = 'ADD_COMPANY';
const LOAD_COMPANY_LIST = 'LOAD_COMPANY_LIST';

export { TOGGLE_THEME, LOGIN_USER, ADD_COMPANY, LOAD_COMPANY_LIST };
