const TOGGLE_THEME = 'TOGGLE_THEME';
const LOGIN_USER = 'LOGIN_USER';
const LOAD_COMPANY_LIST = 'LOAD_COMPANY_LIST';
const ADD_COMPANY = 'ADD_COMPANY';

export {
  TOGGLE_THEME,
  LOGIN_USER,
  LOAD_COMPANY_LIST,
  ADD_COMPANY,
};
